### ISSUE TITLE
osascript error

### ISSUE THREAD

**Issue by Argon-** [steinuil/mpv-livetweet#2]
In https://github.com/steinuil/mpv-livetweet/blob/master/mpv-livetweet.lua#L91 there's a `\'` missing at the end.

Even better:

```
command = 'osascript -e \'set tweet to text returned of (disp' ..
    'lay dialog "" with title "Tweet body" default answer " ' .. hashtag .. '" buttons ' ..
    "Tweet" default button 1)\' -e \'do shell script "echo " & quoted form of tweet\''
```

Now it won't spawn an additional "app" in your dock like it did before (at least for me).
And while we're at it: I had to change `Shift+Alt+w` to `Alt+W` (same for `c`) (`mp.add_key_binding` calls) to make it work for me.

**Comment by steinuil** [comment]
Thank you! I haven't had the chance to test this on a Mac recently and I didn't double check when  changing the code (as usual).
I used OS X 10.7 when I first wrote this so I think the "tell application mpv" part was to fix an issue with previous versions of osascript, it threw an error if you spawned a dialog without "telling" an application to do it. Gotta love AppleScript.
